### ISSUE TITLE
文章跑版及圖片失效

### ISSUE THREAD

**Issue by EvanceKao** [andrew0928/columns.chicken-house.net#9]
https://columns.chicken-house.net/2016/03/12/cpu_sinewave/

這篇文章有跑版及圖片失效的情況，甚至有些 html 原始碼是直接顯示在頁面上的。

**Comment by andrew0928** [comment]
先前從 wordpress 轉過來，HTML -> MD 會跑版
稍後

**Comment by andrew0928** [comment]
fixed
